### ISSUE TITLE
WebBLE

### ISSUE THREAD

**Issue by brandonros** [jglim/OkayCAN#2]
https://github.com/bri3d/esp32-isotp-ble-bridge

You should make it compatible with this firmware.

**Comment by brandonros** [comment]
You only support WiFi, forogt.

**Comment by jglim** [comment]
Yes, unfortunately the esp32-s2 does not appear to be capable of BLE too.

https://www.espressif.com/sites/default/files/documentation/esp32-s2_datasheet_en.pdf
https://www.adafruit.com/product/4653

_".. Also, thee is no Bluetooth support. However, we are super excited about the ESP32-S2's native USB which unlocks a lot of capabilities for advanced interfacing!"_

**Comment by brandonros** [comment]
Which ESP32 chip has BLE?

**Comment by jglim** [comment]
ESP32 (non-s2)
https://www.espressif.com/sites/default/files/documentation/esp32_datasheet_en.pdf
`5.8 Bluetooth LE Radio`

As far as I know, ESP32-C3 has BLE as well. S2 is a strange outlier which does not have any bluetooth (regular and LE) support, which is a shame since it is the only variant with native USB.

**Comment by brandonros** [comment]
which does macchina a0 use? you should update your schematic to use that. bigger market for BLE than USB in my opinion.

i’m not a fan of flashing cars wirelessly on a $1 piece of silicon but hey…

**Comment by jglim** [comment]
Looks like a regular esp32 (ESP32-WROVER-E)
https://github.com/macchina/a0-hardware/blob/master/A0%20Schematic%20Production.pdf

I'll keep your feedback in mind about the esp32 and BLE if the board is redesigned.
